//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1026
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections.Generic;
namespace AssemblyCSharpfirstpass
{
	public class AIBase
	{
		private int currentBehavior;
		private List<AIBehavior> behaviors;
		public AIBase ()
		{
			currentBehavior = 0;

		}

		public void AddBehavior(AIBehavior behavior){
			behaviors.Add (behavior);
		}

		public void switchBehavior(int index){
			currentBehavior = index;
		}

		public virtual void Behave(){

		}

		public void Update(){
			Behave ();
		}
	}
}

