//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1026
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
namespace AssemblyCSharpfirstpass
{
	public class AIBehavior
	{
		private GameObject _gObject;

		public AIBehavior ()
		{
			_gObject = null;
		}

		public AIBehavior (GameObject obj){
			_gObject = obj;
		}

		public virtual void Update(){
		}
	}
}

