//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1026
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
namespace AssemblyCSharpfirstpass
{
	public class AIBehavior
	{
		private GameObject _gObject;
		public Vector2 _target;
		public AIBehavior ()
		{
			_gObject = null;
		}

		public AIBehavior (GameObject obj){
			_gObject = obj;
		}


		public virtual void Update(){

		}

		public virtual GameObject GObject{
			get{ return _gObject;}
		}

		public virtual Vector2 Target{
			get{ return _target;}
			set{ _target = value;}
		}
	}
}

